In [1]:
import numpy as np
import math
np.set_printoptions(formatter={'float': '{: 0.4f}'.format})

In [2]:

gamma = 1
sigma_plus = np.array([[0,1],
                       [0,0]])
sigma_minus = sigma_plus.transpose()


def f(t, ro):
    xx = np.matmul(sigma_plus, sigma_minus)
    s1 = np.matmul(xx, ro)
    
    xx = np.matmul(ro, sigma_plus)
    s2 = np.matmul(xx, sigma_minus)
    
    xx = np.matmul(sigma_minus, ro)
    s3 = np.matmul(xx, sigma_plus)
    return -gamma/2 * (s1 + s2 - 2 * s3)

a = 0
b = 10 
N = 20
ro_0 =np.array([[1.0, 0.0],
              [0.0, 0.0]]) 

h = (b-a)/N
t = a
w = ro_0
print (w,t)

for i in range(1, N + 1):
    w = w + h * f(t,w)
    t = a + i * h
    print (w,t)

[[ 1.0000  0.0000]
 [ 0.0000  0.0000]] 0
[[ 0.5000  0.0000]
 [ 0.0000  0.5000]] 0.5
[[ 0.2500  0.0000]
 [ 0.0000  0.7500]] 1.0
[[ 0.1250  0.0000]
 [ 0.0000  0.8750]] 1.5
[[ 0.0625  0.0000]
 [ 0.0000  0.9375]] 2.0
[[ 0.0312  0.0000]
 [ 0.0000  0.9688]] 2.5
[[ 0.0156  0.0000]
 [ 0.0000  0.9844]] 3.0
[[ 0.0078  0.0000]
 [ 0.0000  0.9922]] 3.5
[[ 0.0039  0.0000]
 [ 0.0000  0.9961]] 4.0
[[ 0.0020  0.0000]
 [ 0.0000  0.9980]] 4.5
[[ 0.0010  0.0000]
 [ 0.0000  0.9990]] 5.0
[[ 0.0005  0.0000]
 [ 0.0000  0.9995]] 5.5
[[ 0.0002  0.0000]
 [ 0.0000  0.9998]] 6.0
[[ 0.0001  0.0000]
 [ 0.0000  0.9999]] 6.5
[[ 0.0001  0.0000]
 [ 0.0000  0.9999]] 7.0
[[ 0.0000  0.0000]
 [ 0.0000  1.0000]] 7.5
[[ 0.0000  0.0000]
 [ 0.0000  1.0000]] 8.0
[[ 0.0000  0.0000]
 [ 0.0000  1.0000]] 8.5
[[ 0.0000  0.0000]
 [ 0.0000  1.0000]] 9.0
[[ 0.0000  0.0000]
 [ 0.0000  1.0000]] 9.5
[[ 0.0000  0.0000]
 [ 0.0000  1.0000]] 10.0
